### ISSUE TITLE
is_null_pointer.h有误

### ISSUE THREAD

**Issue by kevinying16** [namespaceciel/TinySTLbyCiel#2]
is_null_pointer.h里面 struct is_null_pointer : ciel::is_same<nullptr_t, ciel::remove_cv_t> {}; [nullptr_t](error: 'nullptr_t' was not declared in this scope; did you mean 'std::nullptr_t'?)，直接复制的clion给的错误

**Comment by namespaceciel** [comment]
你好，我本地 clion 是能跑通的啊，请问你的环境是。。
